# Generated by Django 5.1 on 2024-08-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('creditCard', models.CharField(choices=[('visa', 'Visa'), ('americanExpress', 'American Express')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('payType', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.IntegerField(unique=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('description', models.CharField(max_length=50)),
                ('payType', models.CharField(choices=[('cash', 'Cash'), ('cc', 'Credit Card'), ('bank', 'Bank')], max_length=50)),
                ('creditCard', models.CharField(choices=[('visa', 'Visa'), ('americanExpress', 'American Express')], max_length=50)),
                ('category', models.CharField(choices=[('groceries', 'Groceries/Home Goods'), ('internet', 'Internet Bill'), ('gasBill', 'Gas Bill'), ('electricBill', 'Electric Bill'), ('waterBill', 'Water Bill'), ('disney', 'Disney/Hulu'), ('gasoline', 'Gasoline/Maintenance'), ('hobbies', 'Hobbies'), ('outsideFood', 'Outside Food'), ('homeRepairs', 'Home Repairs'), ('mortgage', 'Mortgage'), ('other', 'Other')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('cashOrBank', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('expense', 'Expense'), ('ccPayment', 'Credit Card Payment'), ('withdrawl', 'Withdrawl'), ('income', 'Income')], max_length=50)),
                ('year', models.SmallIntegerField(choices=[(2022, 2022), (2023, 2023), (2024, 2024)])),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20)),
                ('monthYear', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('typeMonthYear', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
    ]
