# Generated by Django 5.1 on 2024-08-15 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='monthYear',
        ),
        migrations.AddField(
            model_name='expense',
            name='typeMonthYear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expensetracker.sheet'),
        ),
    ]
