# Generated by Django 5.1 on 2024-08-15 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0002_remove_sheet_monthyear_expense_typemonthyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='transaction',
        ),
    ]
