# Generated by Django 5.1 on 2024-08-17 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0004_alter_income_options_income_typemonthyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardpayment',
            name='typeMonthYear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expensetracker.sheet'),
        ),
        migrations.AddField(
            model_name='withdrawl',
            name='typeMonthYear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expensetracker.sheet'),
        ),
    ]
